### ISSUE TITLE
Piston Crash

### ISSUE THREAD

**Issue by Loxding** [mt1006/mc-nbtac-mod#18] opened 2024-02-01 13:18 UTC
Every single time I use a piston my game just crashes when I'm not using the mod this doesn't happen
Here is the log: https://mclo.gs/5mFbwAo it could be another mod conflicting with it but its weird that it happens with only a piston and not a chat message or something since its a mod that edits chat and command blocks for the client.

**Comment by mt1006** [comment] 2024-02-01 16:42
Could you also send your modpack?

**Comment by Loxding** [comment] 2024-02-01 17:50
https://www.mediafire.com/file/5nuss95aeu8arck/Horribly_Overloaded_1.0.0.mrpack/file
my graphics card is also semi outdated so that might also be the case

**Comment by mt1006** [comment] 2024-02-01 22:28
This has nothing to do with hardware. I was able to recreate this issue and it appears when NBTac, Lithium, ModernFix and More Culling are all installed (with Fabric API and Cloth Config API as dependencies). It could probably be fixed with some "hacky" solution, but it's a part of a larger issue with how NBTac loads classes of entities and block entities. I'm currently working on implementing cache in 1.2, which would partially fix this issue - it would appear only on the first run of a specific modpack. I also plan to rebuild how classes are loaded, which would fully fix the issue, but I'm not sure if it won't introduce any new issues.

For now, the best solution for you is to go to the ```config/nbt_ac.txt``` and set ```use_disassembler = false```. That way it will only load suggestions for items. As for any updates in the matter, I will send them here, and close the issue only when I'll rebuild class loading method. Anyway, thanks for reporting.

**Comment by peow** [comment] 2024-02-06 00:03
wow, this is bad
I would really like to use this mod in my modpack, when you manage to fix this problem I ask you to post an update for fabric 1.20.1 with support for fabric loader 0.14.22

**Comment by mt1006** [comment] 2024-02-06 14:24
Ok, I will.

**Comment by mt1006** [comment] 2024-02-19 10:22
A few updates on the matter:
1. I won't update the way classes are loaded. First, I don't think there exists better solution than the current one. The solutions that I found would be hard to implement, most likely less efficient, inferior, and would probably introduce more issues than fix. Second, I think it wouldn't even fix this particular issue.
2. I'll fix the issue on the NBTac side, but in general it is caused by the compatibility issue between More Culling and ModernFix's dynamic resources, which is triggered by Lithium method, which is triggered by NBTac. Therefore another solution is to disable ```mixin.perf.dynamic_resources``` in ```config/modernfix-mixins.properties```, at least until NBTac 1.2 is released.
3. I will try to release the next version before the end of this month, although I'm not promising anything. Somewhere around time of release I'll probably also report this issue on the More Culling or ModernFix repository.

**Closed as completed** 2024-02-24 20:22 UTC
